# Generated by Django 5.1.6 on 2026-04-25 14:57

import api_public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=api_public.models.generate_api_key, editable=False, max_length=80, unique=True)),
                ('name', models.CharField(help_text="Nom de la clé (ex: 'Production', 'Dev local')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Laisser vide pour une clé sans expiration', null=True)),
            ],
            options={
                'verbose_name': 'Public API Key',
                'verbose_name_plural': 'Public API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
