# Generated by Django 5.1.6 on 2026-04-25 14:57

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('auth_required', models.BooleanField(default=True)),
                ('api_key_encrypted', models.CharField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='API image')),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('private', 'Privée')], default='private', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('quota_cost', models.PositiveIntegerField(default=1, help_text='Nombre de crédits consommés par appel à cette API')),
            ],
        ),
        migrations.CreateModel(
            name='APICallQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_input_required', models.BooleanField(default=False)),
                ('example_request', models.TextField(blank=True, null=True)),
                ('example_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('return_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(choices=[('client_credentials', 'Client Credentials'), ('authorization_code', 'Authorization Code'), ('password', 'Resource Owner Password')], default='client_credentials', max_length=30)),
                ('token_url', models.URLField(help_text='URL du serveur OAuth pour obtenir le token')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret_encrypted', models.CharField(max_length=512)),
                ('scope', models.CharField(blank=True, help_text='Scopes séparés par des espaces (ex: read write)', max_length=512, null=True)),
                ('redirect_uri', models.URLField(blank=True, null=True)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chat_value', models.CharField(default='name', max_length=100)),
                ('param_type', models.CharField(choices=[('query', 'Query Parameter'), ('path', 'Path Parameter'), ('body', 'Body Parameter')], max_length=10)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('JSON', 'json')], default='STRING', max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_in_url', models.BooleanField(default=False)),
                ('is_in_body', models.BooleanField(default=True)),
                ('stored_value', models.CharField(blank=True, max_length=255, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
