# Generated by Django 5.1.6 on 2026-04-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_apis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apicallquota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apilog',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_management.api'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_management.api'),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyuserusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_management.api'),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_management.endpoint'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_management.endpoint'),
        ),
        migrations.AddField(
            model_name='header',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='api_management.endpoint'),
        ),
        migrations.AddField(
            model_name='method',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api_management.endpoint'),
        ),
        migrations.AddField(
            model_name='oauthconfig',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_config', to='api_management.api'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api_management.endpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='apicallquota',
            unique_together={('user', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyuserusage',
            unique_together={('user', 'date')},
        ),
    ]
