# Generated by Django 5.1.6 on 2026-05-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyUserUsage',
        ),
    ]
