# Generated by Django 5.1.6 on 2026-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0003_delete_dailyuserusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='image',
        ),
        migrations.RemoveField(
            model_name='api',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='api',
            name='quota_cost',
            field=models.PositiveIntegerField(default=1, help_text='Number of credits consumed per call to this API'),
        ),
    ]
